export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED'

export const SIGN_IN = 'SIGN_IN';
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED'

export const SIGN_OUT = 'SIGN_OUT'

export const GET_KITCHENS = 'GET_KITCHENS';
export const KITCHENS_RECEIVED = 'KITCHENS_RECEIVED';
export const KTICHENS_FAILED = 'KTICHENS_FAILED';


export const ADD_KITCHEN = 'ADD_KITCHEN'
export const ADD_KITCHEN_SUCCESS = 'ADD_KITCHEN_SUCCESS'
export const ADD_KITCHEN_ERROR = 'ADD_KITCHEN_ERROR'

export const DELETE_KITCHEN = 'DELETE_KITCHEN'
export const DELETE_KITCHEN_SUCCESS = 'DELETE_KITCHEN_SUCCESS'
export const DELETE_KITCHEN_ERROR = 'DELETE_KITCHEN_ERROR'

export const UPDATE_KITCHEN = 'UPDATE_KITCHEN'
export const UPDATE_KITCHEN_SUCCESS = 'UPDATE_KITCHEN_SUCCESS'
export const UPDATE_KITCHEN_ERROR = 'UPDATE_KITCHEN_ERROR'

export const GET_RESTAURANTS = 'GET_RESTAURANTS'
export const RESTAURANTS_RECEIVED = 'RESTAURANTS_RECEIVED'
export const RESTAURANTS_FAILED = 'RESTAURANTS_FAILED'